# https://github.com/marketplace/actions/latest-tag
name: Add latest tag to new release
on:
  release:
    types: [published] # This makes it run only when a new released is published

jobs:
  run:
    name: Add/update tag to new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        #  with:
        #    description: Description for the tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
